name: app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  english_words: ^3.1.5

  #Firebase
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1

  #Google Sign
  google_sign_in: ^4.5.9

  flutter_facebook_auth: ^2.0.0

  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
